### ISSUE TITLE
Display state node context

### ISSUE THREAD

**Issue by wpmccormick** [sonntam/node-red-contrib-xstate-machine#31]
How can I display the state node's context?

There is a Node-RED Context Data panel that (should) display Node, Flow, and Global context.

The Node context does not display the xstate Node context.

**Comment by sonntam** [comment]
The state of the machine is displayed in the state-machines sidebar panel.
There is an entry in the dropdown for every instance contained within subflows - even recursively.

![image](https://user-images.githubusercontent.com/6692408/132920045-0d31a651-72ce-4f4e-a5b2-3a3d558254fc.png)
